// frontend/vue/vue-generate-skill/references/code-examples/views/UserManagement.vue
<script setup lang="ts">
// src/views/UserManagement.vue
// 用户管理页（表格 + 分页 + 搜索 + 增删改查）

import { onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import type { FormInstance } from 'element-plus';
import { userApi } from '@/api/modules/user';
import { showError } from '@/utils/toast';
import type { User, UserListParams, UserCreateRequest } from '@/types/user';

const loading = ref(false);
const tableData = ref<User[]>([]);
const total = ref(0);

const query = reactive<UserListParams>({
  page: 1,
  pageSize: 10,
  keyword: '',
});

const dialogVisible = ref(false);
const dialogMode = ref<'create' | 'edit'>('create');
const formRef = ref<FormInstance>();
const form = reactive<UserCreateRequest>({
  username: '',
  nickname: '',
  roles: [],
  tenantId: 1,
});

async function loadData(): Promise<void> {
  loading.value = true;
  try {
    const res = await userApi.list(query);
    tableData.value = res.data.items;
    total.value = res.data.total;
  } catch (err) {
    showError(err);
  } finally {
    loading.value = false;
  }
}

function handleSearch(): void {
  query.page = 1;
  loadData();
}

function handlePageChange(page: number): void {
  query.page = page;
  loadData();
}

function handleAdd(): void {
  dialogMode.value = 'create';
  dialogVisible.value = true;
}

async function handleDelete(row: User): Promise<void> {
  try {
    await ElMessageBox.confirm(`确定删除用户「${row.nickname}」？`, '提示', {
      type: 'warning',
    });
    await userApi.remove(row.id);
    ElMessage.success('删除成功');
    await loadData();
  } catch (err) {
    if (err !== 'cancel') showError(err);
  }
}

async function handleSubmit(): Promise<void> {
  if (!formRef.value) return;
  try {
    await formRef.value.validate();
    if (dialogMode.value === 'create') {
      await userApi.create(form);
      ElMessage.success('创建成功');
    }
    dialogVisible.value = false;
    await loadData();
  } catch (err) {
    if (err instanceof Error) showError(err);
  }
}

onMounted(loadData);
</script>

<template>
  <div class="user-management">
    <AppPageHeader title="用户管理" description="管理系统用户、角色与权限" />

    <el-card>
      <div class="toolbar">
        <el-input
          v-model="query.keyword"
          placeholder="搜索用户名 / 昵称"
          clearable
          style="width: 280px"
          @keyup.enter="handleSearch"
        />
        <el-button type="primary" @click="handleSearch">搜索</el-button>
        <el-button type="primary" plain @click="handleAdd">新增用户</el-button>
      </div>

      <el-table v-loading="loading" :data="tableData" stripe>
        <el-table-column prop="id" label="ID" width="80" />
        <el-table-column prop="username" label="用户名" />
        <el-table-column prop="nickname" label="昵称" />
        <el-table-column label="角色">
          <template #default="{ row }: { row: User }">
            <el-tag v-for="r in row.roles" :key="r" size="small" class="role-tag">
              {{ r }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="createdAt" label="创建时间" width="180" />
        <el-table-column label="操作" width="120" fixed="right">
          <template #default="{ row }: { row: User }">
            <el-button text type="primary" @click="handleDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-model:current-page="query.page"
        v-model:page-size="query.pageSize"
        :total="total"
        layout="total, prev, pager, next, jumper"
        class="pagination"
        @current-change="handlePageChange"
      />
    </el-card>

    <el-dialog v-model="dialogVisible" :title="dialogMode === 'create' ? '新增用户' : '编辑用户'" width="500px">
      <el-form ref="formRef" :model="form" label-width="80px">
        <el-form-item label="用户名" prop="username" required>
          <el-input v-model="form.username" />
        </el-form-item>
        <el-form-item label="昵称" prop="nickname" required>
          <el-input v-model="form.nickname" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleSubmit">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<style scoped>
.toolbar {
  display: flex;
  gap: var(--space-2);
  margin-bottom: var(--space-4);
}

.role-tag {
  margin-right: var(--space-1);
}

.pagination {
  margin-top: var(--space-4);
  justify-content: flex-end;
}
</style>

// frontend/react/react-generate-skill/references/code-examples/pages/UserManagement.tsx
// src/pages/UserManagement.tsx
// 用户管理页（表格 + 分页 + 搜索 + 新增 + 删除）

import { useEffect, useState } from 'react';
import { App, Button, Form, Input, Modal, Pagination, Space, Table, Tag } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { userApi } from '@/api/modules/user';
import { showError } from '@/utils/toast';
import type { User, UserListParams, UserCreateRequest } from '@/types/user';

interface UserFormValues {
  username: string;
  nickname: string;
  tenantId: number;
}

export function UserManagement() {
  const { message, modal } = App.useApp();
  const [form] = Form.useForm<UserFormValues>();
  const [loading, setLoading] = useState(false);
  const [tableData, setTableData] = useState<User[]>([]);
  const [total, setTotal] = useState(0);
  const [query, setQuery] = useState<UserListParams>({ page: 1, pageSize: 10, keyword: '' });
  const [createOpen, setCreateOpen] = useState(false);
  const [creating, setCreating] = useState(false);

  async function loadData(params: UserListParams = query): Promise<void> {
    setLoading(true);
    try {
      const res = await userApi.list(params);
      setTableData(res.data.items);
      setTotal(res.data.total);
    } catch (err: unknown) {
      showError(err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSearch = (): void => {
    const next = { ...query, page: 1 };
    setQuery(next);
    loadData(next);
  };

  const handlePageChange = (page: number, pageSize: number): void => {
    const next = { ...query, page, pageSize };
    setQuery(next);
    loadData(next);
  };

  const handleCreate = async (): Promise<void> => {
    let values: UserFormValues;
    try {
      values = await form.validateFields();
    } catch {
      return;
    }

    const data: UserCreateRequest = {
      username: values.username,
      nickname: values.nickname,
      roles: ['user'],
      tenantId: values.tenantId,
    };
    setCreating(true);
    try {
      await userApi.create(data);
      message.success('创建成功');
      setCreateOpen(false);
      form.resetFields();
      await loadData();
    } catch (err: unknown) {
      showError(err);
    } finally {
      setCreating(false);
    }
  };

  const handleDelete = (row: User): void => {
    modal.confirm({
      title: '提示',
      content: `确定删除用户「${row.nickname}」？`,
      okButtonProps: { danger: true },
      onOk: async () => {
        try {
          await userApi.remove(row.id);
          message.success('删除成功');
          await loadData();
        } catch (err: unknown) {
          showError(err);
        }
      },
    });
  };

  const columns: ColumnsType<User> = [
    { title: 'ID', dataIndex: 'id', width: 80 },
    { title: '用户名', dataIndex: 'username' },
    { title: '昵称', dataIndex: 'nickname' },
    {
      title: '角色',
      dataIndex: 'roles',
      render: (roles: string[]) => roles.map((role) => <Tag key={role}>{role}</Tag>),
    },
    { title: '创建时间', dataIndex: 'createdAt', width: 180 },
    {
      title: '操作',
      width: 120,
      render: (_, row) => (
        <Button type="link" danger onClick={() => handleDelete(row)}>
          删除
        </Button>
      ),
    },
  ];

  return (
    <div>
      <Space style={{ width: '100%', justifyContent: 'space-between', marginBottom: 16 }}>
        <Space>
          <Input
            placeholder="搜索用户名 / 昵称"
            allowClear
            style={{ width: 280 }}
            value={query.keyword}
            onChange={(e) => setQuery({ ...query, keyword: e.target.value })}
            onPressEnter={handleSearch}
          />
          <Button type="primary" onClick={handleSearch}>
            搜索
          </Button>
        </Space>
        <Button type="primary" onClick={() => setCreateOpen(true)}>
          新增用户
        </Button>
      </Space>

      <Table<User>
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={tableData}
        pagination={false}
      />
      <Pagination
        style={{ marginTop: 16, textAlign: 'right' }}
        current={query.page}
        pageSize={query.pageSize}
        total={total}
        showTotal={(value) => `共 ${value} 条`}
        onChange={handlePageChange}
      />

      <Modal
        title="新增用户"
        open={createOpen}
        onOk={handleCreate}
        onCancel={() => setCreateOpen(false)}
        confirmLoading={creating}
        okText="确定"
        cancelText="取消"
        destroyOnClose
      >
        <Form
          form={form}
          layout="vertical"
          initialValues={{ tenantId: 1 }}
          preserve={false}
        >
          <Form.Item
            label="用户名"
            name="username"
            rules={[{ required: true, message: '请输入用户名' }, { min: 3, max: 32 }]}
          >
            <Input placeholder="请输入用户名" />
          </Form.Item>
          <Form.Item
            label="昵称"
            name="nickname"
            rules={[{ required: true, message: '请输入昵称' }]}
          >
            <Input placeholder="请输入昵称" />
          </Form.Item>
          <Form.Item label="租户" name="tenantId" rules={[{ required: true }]}>
            <Input type="number" />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}
