// frontend/vue/vue-generate-skill/references/code-examples/components/AppLayout.vue
<script setup lang="ts">
// src/components/AppLayout.vue
// 全局布局组件（必备）

import { computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useAppStore } from '@/stores/modules/app';
import { useUserStore } from '@/stores/modules/user';

interface Props {
  /** 是否显示侧边栏 */
  showSidebar?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  showSidebar: true,
});

const emit = defineEmits<{
  /** 登出事件 */
  logout: [];
}>();

const route = useRoute();
const router = useRouter();
const appStore = useAppStore();
const userStore = useUserStore();

const activeMenu = computed<string>(() => route.path);
const breadcrumb = computed<string[]>(() => appStore.breadcrumb);

function handleLogout(): void {
  userStore.logout();
  emit('logout');
  router.push('/login');
}
</script>

<template>
  <el-container class="app-layout">
    <el-aside v-if="props.showSidebar" :width="appStore.sidebarCollapsed ? '64px' : '240px'" class="app-layout__aside">
      <div class="app-layout__logo">
        <span v-if="!appStore.sidebarCollapsed">My App</span>
        <span v-else>MA</span>
      </div>
      <el-menu :default-active="activeMenu" router :collapse="appStore.sidebarCollapsed">
        <el-menu-item index="/">
          <el-icon><HomeFilled /></el-icon>
          <template #title>首页</template>
        </el-menu-item>
        <el-menu-item index="/users">
          <el-icon><User /></el-icon>
          <template #title>用户管理</template>
        </el-menu-item>
      </el-menu>
    </el-aside>

    <el-container>
      <el-header class="app-layout__header">
        <div class="app-layout__header-left">
          <el-button text @click="appStore.toggleSidebar">
            <el-icon><Expand v-if="appStore.sidebarCollapsed" /><Fold v-else /></el-icon>
          </el-button>
          <el-breadcrumb :separator="'/'">
            <el-breadcrumb-item v-for="(item, idx) in breadcrumb" :key="idx">
              {{ item }}
            </el-breadcrumb-item>
          </el-breadcrumb>
        </div>
        <div class="app-layout__header-right">
          <el-dropdown @command="handleLogout">
            <span class="app-layout__user">
              <el-avatar :size="32" :src="userStore.profile?.avatar">
                {{ userStore.profile?.nickname?.charAt(0) }}
              </el-avatar>
              <span>{{ userStore.profile?.nickname }}</span>
            </span>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item>个人中心</el-dropdown-item>
                <el-dropdown-item divided command="logout">退出登录</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </div>
      </el-header>

      <el-main class="app-layout__main">
        <router-view v-slot="{ Component }">
          <transition name="fade" mode="out-in">
            <component :is="Component" />
          </transition>
        </router-view>
      </el-main>
    </el-container>
  </el-container>
</template>

<style scoped lang="scss">
.app-layout {
  height: 100vh;

  &__aside {
    background: var(--color-bg-secondary);
    transition: width 0.2s;
  }

  &__logo {
    height: 60px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: var(--font-lg);
    font-weight: 600;
    color: var(--color-primary);
  }

  &__header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0 var(--space-6);
    background: var(--color-bg);
    border-bottom: 1px solid var(--color-border);
  }

  &__header-left {
    display: flex;
    align-items: center;
    gap: var(--space-4);
  }

  &__user {
    display: flex;
    align-items: center;
    gap: var(--space-2);
    cursor: pointer;
  }

  &__main {
    padding: var(--space-6);
    overflow-y: auto;
  }
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.15s;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// frontend/react/react-generate-skill/references/code-examples/components/AppLayout.tsx
// src/components/AppLayout.tsx
// 全局布局组件（必备）：侧边栏 + 顶部栏 + 内容区

import { useMemo } from 'react';
import { Breadcrumb, Button, Dropdown, Layout, Menu, theme } from 'antd';
import type { MenuProps } from 'antd';
import {
  HomeOutlined,
  UserOutlined,
  LogoutOutlined,
} from '@ant-design/icons';
import { Outlet, useLocation, useNavigate } from 'react-router-dom';
import { useAppStore } from '@/stores/appStore';
import { useUserStore } from '@/stores/userStore';

interface AppLayoutProps {
  /** 是否显示侧边栏 */
  showSidebar?: boolean;
}

export function AppLayout({ showSidebar = true }: AppLayoutProps) {
  const location = useLocation();
  const navigate = useNavigate();
  const { token: themeToken } = theme.useToken();
  const { sidebarCollapsed, breadcrumb, toggleSidebar } = useAppStore();
  const userStore = useUserStore();

  const menuItems: MenuProps['items'] = useMemo(
    () => [
      { key: '/', icon: <HomeOutlined />, label: '首页' },
      { key: '/users', icon: <UserOutlined />, label: '用户管理' },
    ],
    [],
  );

  const handleLogout = (): void => {
    userStore.logout();
    navigate('/login');
  };

  const userMenuItems: MenuProps['items'] = [
    { key: 'logout', icon: <LogoutOutlined />, label: '退出登录', onClick: handleLogout },
  ];

  return (
    <Layout style={{ minHeight: '100vh' }}>
      {showSidebar && (
        <Layout.Sider
          width={240}
          collapsible
          collapsed={sidebarCollapsed}
          onCollapse={toggleSidebar}
          style={{ background: themeToken.colorBgContainer }}
        >
          <div
            style={{
              height: 32,
              margin: 16,
              color: themeToken.colorTextPrimary,
              fontWeight: 600,
              textAlign: 'center',
              lineHeight: '32px',
            }}
          >
            {sidebarCollapsed ? 'MA' : 'My App'}
          </div>
          <Menu
            mode="inline"
            selectedKeys={[location.pathname]}
            items={menuItems}
            onClick={({ key }) => navigate(key)}
          />
        </Layout.Sider>
      )}
      <Layout>
        <Layout.Header
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            background: themeToken.colorBgContainer,
            padding: '0 16px',
          }}
        >
          <Breadcrumb
            items={breadcrumb.map((item) => ({ title: item }))}
          />
          <Dropdown menu={{ items: userMenuItems }}>
            <Button type="text">
              {userStore.profile?.nickname ?? '未登录'} <LogoutOutlined />
            </Button>
          </Dropdown>
        </Layout.Header>
        <Layout.Content style={{ padding: 16 }}><Outlet /></Layout.Content>
      </Layout>
    </Layout>
  );
}
